name: Fisiocontrol CI
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - run: ./mvnw quarkus:test -Dquarkus.test.disable-continuous-testing=true
      - uses: codecov/codecov-action@v3
        name: Upload coverage reports to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          verbose: true
