name: Fisiocontrol CI
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          files: ./coverage1.xml,./coverage2.xml
          fail_ci_if_error: true
          verbose: true
